# Generated by Django 4.2.2 on 2024-12-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, help_text='Опишите товар', max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите стоимость товара', null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, help_text='Введите название товара', max_length=50, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_ad', to='callboard.ad', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания объявления'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, help_text='Введите текст отзыва', max_length=50, null=True, verbose_name='Текст отзыва'),
        ),
    ]
